apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  namespace: tienda-musica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: local-path # Descomenta y ajusta si tienes una StorageClass específica en tu VPS (ej: local-path, hostpath, standard)
