apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvc.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}
  {{- if .Values.database.pvc.storageClassName }}
  storageClassName: {{ .Values.database.pvc.storageClassName }}
  {{- end }}
